"use client";

import Image from "next/image";
import Link from "@/components/native-link";
import { useQuery } from "@tanstack/react-query";
import { Activity, ArrowLeft, CalendarCheck, Clock3, RefreshCw, ShieldCheck, Stethoscope, TicketCheck, TriangleAlert, Users } from "lucide-react";
import { apiJson } from "@/types/clinic";

type Booking = { id: string; status: string; serviceName: string; scheduledAt: number; tokenNumber: number | null; queueStatus: string | null; estimatedWaitSeconds: number | null };
export function BookingStatus({ id }: { id: string }) { const query=useQuery({queryKey:["public-booking",id],queryFn:()=>apiJson<{booking:Booking & {patientsAhead?:number|null}}>(`/api/public/bookings/${id}`),refetchInterval:15000}); if(query.isLoading)return <main className="booking-site"><div className="track-card skeleton" /></main>; if(query.isError||!query.data)return <main className="booking-site"><section className="track-card error-state"><TriangleAlert/><h1>Booking status unavailable</h1><p>{query.error?.message}</p><Link href="/book"><ArrowLeft/>Back to booking</Link></section></main>; const item=query.data.booking; const wait=item.estimatedWaitSeconds==null?null:Math.max(0,Math.round(item.estimatedWaitSeconds/60)); return <main className="booking-site"><div className="booking-container narrow-booking"><header className="booking-brand compact"><Image src="/twacha-logo.png" alt="Twacha" width={1254} height={499}/></header><section className="track-card"><header><div><p className="eyebrow">BOOKING STATUS</p><h1>{item.queueStatus==="IN_CONSULTATION"?"It’s your turn.":item.tokenNumber?"Your queue is live.":"Your appointment is confirmed."}</h1></div><button type="button" onClick={()=>query.refetch()} aria-label="Refresh status"><RefreshCw/></button></header>{item.tokenNumber&&<div className="token-hero"><span><TicketCheck/>Your token</span><b>T-{item.tokenNumber}</b><small>{item.queueStatus?.toLowerCase().replaceAll("_"," ")}</small></div>}<div className="track-grid"><article><CalendarCheck/><span><small>Appointment</small><b>{new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Kolkata"}).format(item.scheduledAt)}</b></span></article><article><Stethoscope/><span><small>Service</small><b>{item.serviceName}</b></span></article><article><Users/><span><small>Patients ahead</small><b>{item.patientsAhead==null?"—":item.patientsAhead}</b></span></article><article><Clock3/><span><small>Estimated wait</small><b>{wait==null?"Not started":wait===0?"Now":`~${wait} minutes`}</b></span></article></div><div className="estimate-disclaimer"><Activity/><span><b>Live operational estimate</b><small>Calculated from the current queue and typical service duration. It is not an AI prediction.</small></span></div><div className="privacy-note"><ShieldCheck/><p><b>Protected status view</b><span>The expiring link exposes no patient name, contact details, or clinical notes.</span></p></div></section><Link className="back-booking-link" href="/book"><ArrowLeft/>Back to Twacha booking</Link></div></main>; }
