"use client";
import {useState} from "react";
import {ArrowRight,CalendarBlank,CaretDown,Check,Clock,Heart,MapPin,ShieldCheck,Sparkle,Star,X} from "@phosphor-icons/react";

const concerns=["Acne & marks","Hair fall","Pigmentation","Laser hair reduction"];
const slots=["10:30 AM","12:00 PM","4:30 PM"];

export default function Home(){
 const [open,setOpen]=useState(false),[step,setStep]=useState(0),[concern,setConcern]=useState(""),[slot,setSlot]=useState(""),[name,setName]=useState(""),[phone,setPhone]=useState("");
 const start=()=>{setOpen(true);setStep(0)};
 const confirm=()=>{localStorage.setItem("supreme-latest-appointment",JSON.stringify({id:`SUP-${Date.now().toString().slice(-5)}`,name,phone,treatment:concern,slot,date:"2026-08-23",status:"Confirmed"}));setStep(3)};
 return <main>
  <header className="nav shell"><a className="brand" href="#top"><span className="brand-mark">S</span><span><b>SUPREME</b><small>HAIR &amp; SKIN CARE</small></span></a><nav><a href="#care">Care</a><a href="#approach">Our approach</a><a href="#visit">Visit</a></nav><button className="button compact" onClick={start}>Book a visit <ArrowRight/></button></header>
  <section className="hero shell" id="top"><img src="./clinic-consultation.webp" alt="Dermatologist listening to a patient during a consultation"/><div className="hero-copy"><p className="eyebrow">Dermatologist-led care in Hubballi</p><h1>Care that feels<br/><em>personal.</em></h1><p className="lede">Clear answers, thoughtful treatment and skin &amp; hair care designed around you.</p><div className="hero-actions"><button className="button" onClick={start}><Sparkle weight="fill"/> Help me choose <ArrowRight/></button><a href="#care">Explore care</a></div><div className="hero-proof"><span><Star weight="fill"/> 4.8 patient rating</span><span>Private, guided booking</span></div></div></section>
  <section className="trust shell"><span><ShieldCheck/> Evidence-led care</span><span><Clock/> Appointments that respect your time</span><span><Heart/> Support that listens</span></section>
  <section className="section shell" id="care"><div className="section-heading"><div><p className="eyebrow">Common concerns</p><h2>Start with what’s bothering you.</h2></div><p>You don’t need to know the treatment. Tell us the concern and we’ll guide you.</p></div><div className="concern-grid">{concerns.map((item,i)=><button key={item} onClick={()=>{setConcern(item);setOpen(true);setStep(1)}}><span>0{i+1}</span><b>{item}</b><ArrowRight/></button>)}</div></section>
  <section className="approach" id="approach"><div className="shell approach-inner"><div><p className="eyebrow light">A calmer first step</p><h2>One conversation.<br/>A clearer path.</h2></div><ol><li><span>01</span><div><b>Share your concern</b><p>Use your own words or choose what feels closest.</p></div></li><li><span>02</span><div><b>Get a thoughtful recommendation</b><p>The assistant suggests a consultation and explains why.</p></div></li><li><span>03</span><div><b>Choose a time</b><p>See slots and request your visit in under two minutes.</p></div></li></ol><button className="button peach" onClick={start}>Start with the concierge <ArrowRight/></button></div></section>
  <section className="section shell stories"><div className="section-heading"><div><p className="eyebrow">Why patients choose Supreme</p><h2>Thoughtful care, without the rush.</h2></div></div><div className="quote"><div className="stars">{[1,2,3,4,5].map(n=><Star key={n} weight="fill"/>)}</div><blockquote>“The consultation felt clear and unhurried. I understood my options before deciding anything.”</blockquote><p>Verified patient feedback · Hubballi</p></div></section>
  <section className="visit shell" id="visit"><div><p className="eyebrow">Plan your visit</p><h2>Supreme Hair &amp; Skin Care</h2><p>Hubballi, Karnataka</p></div><div className="visit-meta"><span><CalendarBlank/><b>Monday – Saturday</b><small>Appointments available</small></span><span><MapPin/><b>Central Hubballi</b><small>Directions shared on confirmation</small></span></div><button className="button" onClick={start}>Find a slot <ArrowRight/></button></section>
  <section className="section shell faq"><p className="eyebrow">Good to know</p><h2>Before your visit</h2>{["Do I need to know which treatment I want?","Is the AI assistant giving medical advice?","What happens after I request a slot?"].map((q,i)=><details key={q}><summary>{q}<CaretDown/></summary><p>{i===0?"No. Begin with your concern and the clinic can recommend the right consultation.":i===1?"No. It helps route your concern and arrange an appointment. Diagnosis belongs to a qualified clinician.":"Your request is saved and the clinic team can confirm the appointment with you directly."}</p></details>)}</section>
  <section className="final-cta shell"><div><p className="eyebrow">Ready when you are</p><h2>Your care starts with a conversation.</h2></div><button className="button" onClick={start}><Sparkle weight="fill"/> Help me choose</button></section>
  <footer className="shell"><a className="brand" href="#top"><span className="brand-mark">S</span><span><b>SUPREME</b><small>HAIR &amp; SKIN CARE</small></span></a><p>Thoughtful hair and skin care in Hubballi.</p><small>Demo experience. The AI concierge does not provide medical advice or diagnosis.</small></footer>
  {open&&<div className="modal-backdrop" onMouseDown={()=>setOpen(false)}><section className="concierge" role="dialog" aria-modal="true" aria-label="AI care concierge" onMouseDown={e=>e.stopPropagation()}><header><div><Sparkle weight="fill"/><span><b>Care concierge</b><small>AI-guided · about 1 minute</small></span></div><button aria-label="Close booking" onClick={()=>setOpen(false)}><X/></button></header><div className="progress"><i style={{width:`${(step+1)*25}%`}}/></div><div className="chat">
   {step===0&&<><div className="bubble ai">Hi, I’m here to help you find the right first step. What would you like support with?</div><div className="choices">{concerns.map(c=><button key={c} onClick={()=>{setConcern(c);setStep(1)}}>{c}<ArrowRight/></button>)}</div><p className="privacy"><ShieldCheck/> Private by design. Guidance, not a diagnosis.</p></>}
   {step===1&&<><div className="bubble user">I’d like help with {concern.toLowerCase()}.</div><div className="bubble ai">Thanks for sharing. A <b>{concern.includes("Hair")?"hair and scalp consultation":"skin consultation"}</b> is the best place to begin. A clinician can understand the cause and discuss suitable options.</div><p className="assistant-note">Here are the next available times.</p><div className="slots">{slots.map(s=><button className={slot===s?"selected":""} key={s} onClick={()=>setSlot(s)}><small>Tomorrow</small><b>{s}</b>{slot===s&&<Check weight="bold"/>}</button>)}</div><button className="button full" disabled={!slot} onClick={()=>setStep(2)}>Continue with {slot||"a time"} <ArrowRight/></button></>}
   {step===2&&<><div className="bubble ai">Lovely. Who should we reserve this visit for?</div><label>Your name<input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="Full name"/></label><label>Mobile number<input value={phone} onChange={e=>setPhone(e.target.value)} inputMode="tel" placeholder="10-digit number"/></label><button className="button full" disabled={!name||phone.replace(/\D/g,"").length<10} onClick={confirm}>Request my appointment <ArrowRight/></button><p className="privacy">By continuing, you agree to be contacted about this appointment.</p></>}
   {step===3&&<div className="success"><span><Check weight="bold"/></span><p className="eyebrow">Visit requested</p><h2>You’re all set, {name.split(" ")[0]}.</h2><p>Your {concern.toLowerCase()} consultation is reserved for tomorrow at {slot}. The clinic can contact you to confirm.</p><button className="button full" onClick={()=>setOpen(false)}>Done</button></div>}
  </div></section></div>}
 </main>
}